import type { Metadata } from "next";
import { cookies } from "next/headers";

export const metadata: Metadata = {
  title: "Food management system",
  description: "Generated by create next app",
};

const checkNotAuthorized = async (cookies?: string) => {
  if (!cookies) {
    return true;
  }

  const result = await fetch(
    `${process.env.NEXT_PUBLIC_WEB_API_URL}/auth/user_info`,
    {
      headers: {
        Cookie: cookies,
      },
      credentials: "include",
    }
  );

  console.log(result);
};

export default async function OptionalLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const cookieStore = await cookies();

  // await checkNotAuthorized(cookieStore.toString());

  return (
    <div className="flex h-screen items-center justify-center">{children}</div>
  );
}
